---
- name: Update Hostname, Timezone, and User Password
  hosts: all
  gather_facts: false
  vars_prompt:
    - name: ansible_become_password
      prompt: "Enter old user password"
      private: true
      default: temppwd
    - name: new_user_password
      prompt: "Enter new user password (leave empty to skip)"
      private: true
    - name: new_hostname
      prompt: "Enter new hostname"
      default: jetblade
    - name: new_timezone
      prompt: "Enter new timezone"
      default: Asia/Kolkata
  become: true

  tasks:
    - name: Update timezone
      community.general.timezone:
        name: "{{ new_timezone }}"

    - name: Update hostname
      ansible.builtin.hostname:
        name: "{{ new_hostname }}"

    - name: Change hostname for mDNS resolution
      ansible.builtin.replace:
        dest: /etc/hosts
        regexp: '^([0127.]+\s+).+\.localdomain\s+.+$'
        replace: '\1{{ new_hostname }}.localdomain {{ new_hostname }}'

    - name: Add sudoers entry for passwordless apt commands
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/passwordless_apt
        line: "{{ ansible_user }} ALL=(ALL) NOPASSWD: /usr/bin/apt"
        create: true
        owner: root
        group: root
        mode: '0440'
        validate: 'visudo -cf %s'

    - name: Update user password if a new one was provided
      block:
        - name: Update user password
          ansible.builtin.user:
            name: "{{ ansible_user }}"
            password: "{{ new_user_password | password_hash('sha512', 65534) }}"
          when: new_user_password != ""
